name: Build and Deploy Code

on: ["push", "pull_request"]

jobs:
  job1:
      env:
        DATABASE_HOSTNAME: localhost
        DATABASE_PORT: 5432
        DATABASE_PASSWORD: fastapipostpass
        DATABASE_NAME: fastapipost
        DATABASE_USERNAME: fastapipost_user
        SECRET_KEY: fjfjfueruoeieri98439085hj083gj4kfj48jffghgu5j83jgfu5gfj5i39gfjkgijg89iwsmcnvbnbutjntvcx23
        ALGORITHM: HS256
        ACCESS_TOKEN_EXPIRATION_TIME: 300
      runs-on: ubuntu-latest
      steps:
        - name: pulling git repo
          uses: actions/checkout@v2
        - name: Install python version 3.9
          uses: actions/setup-python@v2
          with:
            python-version: "3.14"
        - name: install all dependencies
          run: pip install -r requirements.txt
        - name: test with pytest
          run: |
            pip install pytest
            pytest

        